name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: pytest

deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy Application
        run: |
          ssh ubuntu@100.25.191.235 "if [ ! -d '/home/ubuntu/app' ]; then git clone https://github.com/VikingVik123/fastapi-book-project.git /home/ubuntu/app; fi"
          ssh ubuntu@100.25.191.235 "cd /home/ubuntu/app && git pull origin main && pip3 install -r requirements.txt && nohup uvicorn main:app --host 0.0.0.0 --port 8000 > output.log 2>&1 &"
          ssh ubuntu@100.25.191.235 "sudo apt update && sudo apt install -y nginx"
          ssh ubuntu@100.25.191.235 "echo 'server {
            listen 80;
            server_name your-domain.com;

            location / {
                proxy_pass http://127.0.0.1:8000;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }
          }' | sudo tee /etc/nginx/sites-available/fastapi"
          ssh ubuntu@100.25.191.235 "sudo ln -sf /etc/nginx/sites-available/fastapi /etc/nginx/sites-enabled"
          ssh ubuntu@100.25.191.235 "sudo service nginx restart"
